### ISSUE TITLE
知乎登录页面作业反馈

### ISSUE THREAD

**Issue by twhy** [G-Ling-yy/g-ling-yy.github.io#2]
总体的还原度很好，有一点小小建议。
1. 右下角的图标有点模糊，估计你是自己截图的，你可以尝试 `background-image: url(data:image...B3aWR0aD)` 这种形式，那串 base 64 的图片编码可以从知乎的页面复制过来。
这样可以运用一种新技巧又不用费劲自己截图。

**Comment by G-Ling-yy** [comment]
我在html注释里提到了，那就是我之前截图做的，因为还没来及学习base64，我会及时学习修改的，谢谢老师。

**Comment by twhy** [comment]
@G-Ling-yy 好的👌
